version: "3"

services:
  sms:
    image: nsq_to_shell
    container_name: sms
    restart: always
    command: /nsqlookupd
    environment:
      - GO_MICRO_ENV=pd
    volumes:
      - ./conf/sms.toml:/app/pd.toml
  tel:
    image: nsqio/nsq
    container_name: tel
    restart: always
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161