version: "3"

services:
  sms:
    image: nsq_to_shell
    container_name: sms
    restart: always
    environment:
      - GO_MICRO_ENV=pd
    volumes:
      - ./conf/sms.toml:/app/pd.toml
  tel:
    image: nsq_to_shell
    container_name: tel
    restart: always
    environment:
      - GO_MICRO_ENV=pd
    volumes:
      - ./conf/tel.toml:/app/pd.toml