version: "3"

services:
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    restart: always
    networks:
      - ops
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161:4161"
  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    restart: always
    networks:
      - ops
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    restart: always
    networks:
      - ops
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160  --broadcast-address=127.0.0.1
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
networks:
  ops:
    external: true